tool.facetracker.name=茶茶捕捉
tool.facetracker.desc=将 ARKit 表情系数映射到实体 Flex
tool.facetracker.0=选择要驱动的实体
tool.facetracker.right=选择实体

tool.facetracker.connect=连接面捕服务
tool.facetracker.disconnect=断开面捕服务
tool.facetracker.general=为每个 Flex 设置对应的 ARKit 表情系数
tool.facetracker.help1=点击“连接面捕服务”以连接本机面捕程序
tool.facetracker.help2=ARKit 表情系数范围为 0 到 1，数值代表面部动作的强度
tool.facetracker.expressions=Flex 表情映射
tool.facetracker.eyetracking=眼睛追踪
tool.facetracker.blendshapes=ARKit 表情系数
tool.facetracker.latency=延迟
tool.facetracker.remove=清空表情映射

tool.facetracker.replication.warning=更新频率会影响本机性能和服务器负载。
tool.facetracker.replication.maxinterval=最大更新间隔：
tool.facetracker.replication.interval=更新间隔（毫秒）
tool.facetracker.replication.interval.tooltip=面捕数据发送到服务器的间隔

tool.facetracker.tree=点击模型图标可切换实体
tool.facetracker.presets.selected=当前选择
